version: '3.9'

services:
  postgres-ideas:
    image: postgres:15
    container_name: postgres-ideas
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: ideasdb
    ports:
      - '5440:5432'
    networks:
      - app_network

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: always
    ports:
      - '3002:3002'
    networks:
      - app_network

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: my-nginx
    ports:
      - '80:80'
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
